{{ config(
    materialized='incremental',
    unique_key = "HOST_ID"
) }}

SELECT
    HOST_ID,

    UPPER(TRIM(HOST_NAME)) AS HOST_NAME,

    HOST_SINCE,

    COALESCE(IS_SUPERHOST, FALSE) AS IS_SUPERHOST,

    COALESCE(RESPONSE_RATE, 0) AS RESPONSE_RATE,

    CASE
        WHEN RESPONSE_RATE >= 90 THEN 'EXCELLENT'
        WHEN RESPONSE_RATE >= 75 THEN 'GOOD'
        WHEN RESPONSE_RATE >= 50 THEN 'AVERAGE'
        ELSE 'LOW'
    END AS RESPONSE_RATE_CATEGORY,

    CASE
        WHEN IS_SUPERHOST = TRUE THEN 'SUPERHOST'
        ELSE 'NORMAL_HOST'
    END AS HOST_TYPE,

    DATEDIFF(year, HOST_SINCE, CURRENT_DATE) AS HOST_EXPERIENCE_YEARS,

    CREATED_AT

FROM {{ ref('bronze_hosts') }}