{{ config(
    materialized='incremental',
    unique_key = "LISTING_ID"
) }}

SELECT
    LISTING_ID,

    HOST_ID,

    UPPER(TRIM(PROPERTY_TYPE)) AS PROPERTY_TYPE,

    UPPER(TRIM(ROOM_TYPE)) AS ROOM_TYPE,

    UPPER(TRIM(CITY)) AS CITY,

    UPPER(TRIM(COUNTRY)) AS COUNTRY,

    COALESCE(ACCOMMODATES,0) AS ACCOMMODATES,

    COALESCE(BEDROOMS,0) AS BEDROOMS,

    COALESCE(BATHROOMS,0) AS BATHROOMS,

    CAST(PRICE_PER_NIGHT AS FLOAT) AS PRICE_PER_NIGHT,

    CASE
        WHEN PRICE_PER_NIGHT < 50 THEN 'BUDGET'
        WHEN PRICE_PER_NIGHT < 150 THEN 'STANDARD'
        WHEN PRICE_PER_NIGHT < 300 THEN 'PREMIUM'
        ELSE 'LUXURY'
    END AS PRICE_CATEGORY,

    CASE
        WHEN BEDROOMS = 0 THEN 'STUDIO'
        WHEN BEDROOMS = 1 THEN 'SMALL'
        WHEN BEDROOMS <= 3 THEN 'MEDIUM'
        ELSE 'LARGE'
    END AS PROPERTY_SIZE,

    CASE
        WHEN ACCOMMODATES <= 2 THEN 'SMALL_GROUP'
        WHEN ACCOMMODATES <= 4 THEN 'MEDIUM_GROUP'
        ELSE 'LARGE_GROUP'
    END AS GUEST_CAPACITY_CATEGORY,

    PRICE_PER_NIGHT / NULLIF(BEDROOMS,0) AS PRICE_PER_BEDROOM,

    CREATED_AT

FROM {{ ref('bronze_listings') }}